# -*- coding: utf-8 -*-
"""Maximum a Posteriori .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XVgHDxsdgUeX_roBAuCi4BpuTqL3ZCWb
"""

# Maximum a posteriori Estimation (MAP)

#Seyed Hesamoddin Hosseini
# 24 November

import numpy as np
from numpy import random
from numpy.core.fromnumeric import size
from scipy import stats
import scipy
from scipy.optimize import minimize

my_Exp =np.random.normal(loc=20,scale=6,size=100)
#avgerage prior= AP
AP =16
#variance prior=VP
VP=4
for i in range(0,50):
   teta=my_Exp[i]+AP
teta=teta/1+100

def gaussian(parameters):
    avg=parameters[0]
    variance=parameters[1]
    #sum log= SL
    SL=-np.sum(np.log(stats.norm.pdf(teta,loc=AP,scale=VP) * 
                      stats.norm.pdf(my_Exp,loc=avg,scale=variance)))
    return SL

output=minimize(gaussian,initial).x
print('teta= ',output[0])
print('mean - teta= ',output[0]-20)